socialapp/urls.py
from django.contrib import admin
from django.urls import path,include

from api import views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
router = DefaultRouter()
router.register("users", views.UserView, basename="users")
router.register("posts", views.PostView, basename="posts")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls"))
]+router.urls

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("register/", UserReigtrationView.as_view(), name="sign-up"),
    path("" ,LoginView.as_view(), name="sign-in"),
    path("logout/", sign_out, name="sign-out"),
    path('comments/<int:pk>/delete/', delete_comment, name='delete_comment'),
    path("index/", IndexView.as_view(), name="home"),
    path("people/", ListPeopleView.as_view(), name="people"),
    path("post/<int:id>/comment/add", add_comment, name="add-comment"),
    path("n/post/<int:post_id>/delete",delete_post, name="deletepost"),
    path("post/<int:id>/like/add", like_post, name="like-post"),
    path('posts/<int:pk>/unlike/', unlike_post, name='unlike_post'),
    path("user/<int:id>/follower/add", add_follower, name="add-follower"),
    path("myprofile/",profile, name="myprofile"),
    # path('profile/', profile2,name='profile'),
    path('posts/<int:pk>/like/',like_post, name='like_post'),
    # path('search/', search, name='search'),
    #  path('search', search, name='search'),
    path('comments/<int:pk>/like/',like_comment, name='like_comment'),
    path('comments/<int:pk>/unlike/',unlike_comment, name='unlike_comment'),
]

api/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Posts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    like = models.ManyToManyField(User, related_name='like')
    dislike=models.ManyToManyField(User, related_name='dislike')
    created_date = models.DateField(auto_now_add=True)

    @property
    def likes(self):
        return self.like.all().count()

    @property
    def dislikes(self):
        return self.dislike.all().count()

    @property
    def comments(self):
        return self.comments_set.all()


    @property
    def imageURL(self):
        if self.image:
            return self.image.url
        else:
            return ""

    def __str__(self):
        return self.title


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    liked=models.ManyToManyField(User,related_name="likes",null=True)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.comment

    @property
    def likecounts(self):
        return self.liked.all().count()
class Friends(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    date = models.DateTimeField(auto_now_add=True)

class Profile(models.Model):
      user = models.OneToOneField(User, on_delete=models.CASCADE,null=True,blank=True)
      bio = models.TextField(max_length=500,default="no bio", blank=True)
      following = models.ManyToManyField(User, related_name='following', blank=True)


def __str__(self):
        return f'Profile for user {self.user.username}'

web/templates/post/post_create.html
<div class="card border-0 shadow-sm ms-5" >
    <div class="card-body">
        <div class="input-group" style="width: 100%; height: 3em;">

            <span class="input-group-text border-0 " data-bs-toggle="modal" data-bs-target="#exampleModal"
                id="basic-addon1"></span>
            <input type="text" class="form-control border-1 btn btn-outline-light" placeholder="Add your posts, {{request.user}}. ." aria-label="Username"
                aria-describedby="basic-addon1" data-bs-toggle="modal" data-bs-target="#exampleModal">
        </div>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-2" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-2" id="exampleModalLabel">Add post</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" class="btn btn-info" name="" id="" value="Add post">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>



{% comment %} <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="post" class="btn btn-primary">
</form> {% endcomment %}

web/templates/post/post_list.html
{% for post in posts %}

<div class="card-div mt-4 mb-2 ms-5">
    <div class="card p-2 border border-0 shadow-sm" style="width: 100%">
        <img src="{{post.imageURL}}"class="card-img-top" alt="...">
        <div class="card-body">
            <p class="card-text">{{post.title}}</p>

            <div class="btn-group border border-0" style="width: 100%;;" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-outline-warning shadow-sm text-dark collapsed"
                    data-bs-toggle="collapse" data-bs-target="#flush-collapse{{post.id}}" aria-expanded="false"
                    aria-controls="flush-collapseOne"><i class="fa-solid fa-comment"></i></button>
                
            {% if not request.user in post.likes.all %}
                <a href="{% url 'like-post' post.id %}" type="button" class="btn btn-outline-warning shadow-sm text-dark">{{post.likes}} <i class="fa fa-thumbs-up" aria-hidden="true"></i></a>
                {% else %}
              
                <a href="{% url 'like-post' post.id %}" type="button" class="btn btn-outline-warning shadow-sm text-dark">{{post.likes}} <i class="fa fa-thumbs-down" aria-hidden="true"></i></a>
              {%endif%}
           
              
                
            </div>
            

            <!-- <-- comment section --> 
            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                    <div id="flush-collapse{{post.id}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                        data-bs-parent="#accordionFlushExample" style=>

                        <form action="{% url 'add-comment' post.id %}" method="post">
                            {% csrf_token %}
                            <textarea name="comment" class="form-control" id="id_comment" cols="74" rows="5"></textarea>
                            <input type="submit" value="addcomment" class="btn btn-outline-warning">
                        </form>

                        {% for comment in post.comments %}
                        <div class="accordion-body bg-light m-1 mt-2">
                            <div class="">
                                <img src="images\dp.png" class="border rounded-circle me-2"
                                alt="" style="height: 40px" />
                                <p><small>@{{comment.user}}</small></p>
                                <p>{{comment.comment}}</p>
                                


                                    {% if comment.user == user %}
                                    <a href="{% url 'delete_comment' comment.pk %}"> Delete </a>
                                           
                                    {% endif %}
                            
                                <p><a href="#">
                                    <i class="fas fa-thumbs-up text-primary "></i>
                                    <span>{{ comment.liked.count}}</span>
                                  </a></p>
                                <p>
                                    <a href="#" class="text-muted small ms-3 me-2">
          
                                        {% if user in comment.liked.all %}
                                      <a href="{% url 'unlike_comment' comment.pk %}">Unlike</a>
                                  {% else %}
                                      <a href="{% url 'like_comment' comment.pk %}">Like</a>
                                  {% endif %}
                                 </p>
                          
                            </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- end of comment section -->

            

            
        </div>
    </div>
</div>

{% endfor %}

web/templates/post/yourpost.html
<div class="container d-flex justify-content-center align-items-center">
             
    <div class="card">

     <div class="upper">

       <img src="https://i.imgur.com/Qtrsrk5.jpg" class="img-fluid">
       
     </div>

     <div class="user text-center">

       <div class="profile">

         <img src="https://i.imgur.com/JgYD2nQ.jpg" class="rounded-circle" width="80">
         
       </div>

     </div>


     <div class="mt-5 text-center">

       <h4 class="mb-0">Benjamin Tims</h4>
       <span class="text-muted d-block mb-2">Los Angles</span>

       <button class="btn btn-primary btn-sm follow">Follow</button>


       <div class="d-flex justify-content-between align-items-center mt-4 px-4">

         <div class="stats">
           <h6 class="mb-0">Followers</h6>
           <span>8,797</span>

         </div>


         <div class="stats">
           <h6 class="mb-0">Projects</h6>
           <span>142</span>

         </div>


         <div class="stats">
           <h6 class="mb-0">Ranks</h6>
           <span>129</span>

         </div>
         
       </div>
       
     </div>
      
    </div>

  </div>